---
laout : single
title: "예외 클래스, 예외 처리하기, 예외 처리 미루기, 사용자 정의 예외"
excerpt : "예외 처리"
categories :
- Java
tags :
- [Playdata ,Java]
toc: true #Table of contents 옆에 목록이 생성됨
toc_sticky: true #toc가 화면을 따라 내려옴
toc_label: 목차 #toc 상단에 써있는 제목

date: 2021-10-12
last_modified_at: 2021-10-12
---

자바 교육 15회차
## 예외 클래스

자바는 비정상 종료를 최대한 줄이기 위해 다양한 예외에 대한 처리 방법을 가지고 있습니다. 자바에서 오류 클래스는 모두 java.lang 패캐지에 속한 Throwable 클래스에서 상속 받습니다.

- Throwable
  - Error
  - Exception
    - RuntimeException
      - NullPointerException
      - ArrayIndexOutOfBoundsException
    - IOException

Error : 개발자가 처리할수 없는 프로그램 오류. 물리적 오류
Exception : 개발자가 처리할 수 있는 프로그램 오류.

예외에는 여러 종류가 있는데 크게 RuntimeException과 FileNotFoundException이 있는데 실행시 발생하는 Runtime예외가 많이 나타나고 많이 다루게 될 것입니다.

아래는 RuntimeException 중 가장 많이 나타나는 4가지 예문이다.
```
System.out.println("1");
//----ClassNotFoundException
Class.forName("메롱메롱"); //오류

//----ArrayIndexOutOfBoundsException
int[] arr=new int[3];
arr[3]=30;// 오류발생

//----NullPointerException
String s=new String("ok");
s=null;
s.length();// 오류발생

//----ArithmeticException
int a=(123 / 0);// 오류발생
```

## 예외 처리하기
예외를 처리하는 문법에는 try-catch문, try-catch-finally문이 있습니다.
간단한 try-catch-finally 예제입니다. NullPointerException 경우이지만 상위 객체인 Exception을 이용해서 예외를 처리하였습니다. API 문서를 확인하여 NullPointerException의 상위 객체인지 확인하고 활용하면 좋을 것 같습니다.
```
public static void main(String[] args) {
  try{//예외가 발생할 수 있는 부분입력
    String a = null;
    a.length();
  }catch(Exception e){//처리할 예외 타입
    System.out.println(e);
  }finally{//오류가 있던 없던 실행됨
    System.out.println("무조건 실행!");
  }
}
```

## 예외 처리 미루기
예외를 해당 메서드에서 처리하지 않고 미룬 후 메서드를 호출하여 사용하는 부분에서 예외를 처리하는 방법입니다.
```
public static void main(String[] args) {
  try {
    test();
  } catch (Exception e) {
    //ClassNotFoundException 이지만 Exception으로 처리하였다.
    e.printStackTrace();
  }
}

public static void test() throws ClassNotFoundException, IOException{
  Class.forName("");
  System.in.read();
  //오류가 발생했을때는 메소드 안에서 try - catch를 사용해도돼고
  //throws한 다음 메인에서 처리해도 된다.
}
```

## 사용자 정의 예외
배터리 충전량을 음수로 임력하면 오류가 발생하는 예외를 확인해보겠습니다.
```
public class NegativeNumberException extends Exception {
//선언만해도 된다
	public NegativeNumberException() {
		super("음수는 불허!");//Exception 생성자에 String을 넣어서 오류 메세지 출력
	}
}
```
```
public static void main(String[] args) {
	CellPhone c = new CellPhone();
	try {
		c.charge(30);
		c.charge(20);
		c.charge(-10);
	} catch (NegativeNumberException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}
class CellPhone{
	int battery;

  public void charge(int time) throws NegativeNumberException{
    if(time<0){
      time=0; //오류 발생
      //그냥 throw new NegativeNumberException()하면 오류 발생함
      //try catch문 하거나 메소드에 throws 해줘야함 throws하면 메인에서 try해야함
  		throw new NegativeNumberException();

      /*try {
        throw new NegativeNumberException();
        } catch (NegativeNumberException e) {
          e.printStackTrace();
        }*/
      }
		battery+=time;
		System.out.println("배터리량:"+battery);
	}
}
```

## 다중 예외 처리에서 주의할 점

아래의 예문에서 try - catch문을 작성하는데 Exception이 NumberException의 상위객체이기 때문에 아래쪽 catch문은 버려지는 부분이 되어 오류가 발생한다.
```
try{
  예외가 발생할 수 있는 부분
}catch(Exception e){
  예외 처리하는 부분
}catch(NumberException e){
  예외 처리하는 부분  
}
```
